name: CI - Testes UI e API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes API (Jest)
        run: npm run test:api

      - name: Rodar testes UI (Cypress)
        run: npm run test:ui

      - name: Listar arquivos após testes
        run: ls -R reports/ui

      - name: Gerar relatório Cypress consolidado
        run: |
          rm -f reports/ui/report.json
          if ls reports/ui/mochawesome_*.json 1> /dev/null 2>&1; then
            npm run merge:reports
          else
            echo "Nenhum arquivo JSON encontrado. Verifique a configuração do Mochawesome."
          fi

      - name: Publicar relatórios como artefatos
        uses: actions/upload-artifact@v4
        with:
          name: relatorios
          path: |
            reports/ui
            reports/api
